### ISSUE TITLE
Setup failed for custom integration 'wemportal': Unable to import component: No module named 'cgi'   /  Homeassistant  2024.12.xbx

### ISSUE THREAD

**Issue by maddinhome** [erikkastelec/hass-WEM-Portal#113]
Hello, there seems to be a small error after installing the December BETA of Homeassistant.

Core 2024.12.0b1
Supervisor 2024.11.4
Operating System 14.0.rc2
Frontend 20241127.0

Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 15:26:50 (1 Vorkommnisse)
Zuletzt protokolliert: 15:26:50

Setup failed for custom integration 'wemportal': Unable to import component: No module named 'cgi'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wemportal/__init__.py", line 26, in <module>
    from .coordinator import WemPortalDataUpdateCoordinator
  File "/config/custom_components/wemportal/coordinator.py", line 15, in <module>
    from .wemportalapi import WemPortalApi
  File "/config/custom_components/wemportal/wemportalapi.py", line 13, in <module>
    import scrapyscript
  File "/usr/local/lib/python3.13/site-packages/scrapyscript/__init__.py", line 14, in <module>
    from scrapy import signals
  File "/usr/local/lib/python3.13/site-packages/scrapy/__init__.py", line 12, in <module>
    from scrapy.spiders import Spider
  File "/usr/local/lib/python3.13/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/usr/local/lib/python3.13/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/usr/local/lib/python3.13/site-packages/scrapy/http/request/form.py", line 16, in <module>
    from scrapy.http.response.text import TextResponse
  File "/usr/local/lib/python3.13/site-packages/scrapy/http/response/text.py", line 26, in <module>
    from scrapy.utils.response import get_base_url
  File "/usr/local/lib/python3.13/site-packages/scrapy/utils/response.py", line 15, in <module>
    from twisted.web import http
  File "/usr/local/lib/python3.13/site-packages/twisted/web/http.py", line 103, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'


Maybe it has something to do with the new Phyton version 3.13?

Back with version core_2024.11.3 and it works again.

**Comment by maddinhome** [comment]
Have you seen this: **Back with version core_2024.11.3 and it works again.**

It still works for me... and isn't broken

**Comment by maddinhome** [comment]
There is a note here:

https://docs.python.org/3/library/cgi.html

The next python version in HomeAssistant (2024/12) also has the version number. 3.13 and therefore it is certainly necessary to work on this bug. The new version comes out tomorrow. Otherwise this integration will unfortunately no longer work. That wouldn't be very nice. I like the integration... If I knew the Python programming language I would be happy to help.

**Comment by erikkastelec** [comment]
Thank you for your report. Hope I can find an easy fix

**Comment by Bertk** [comment]
The integration setup fails after HA 2024.12 update (release date 4.12.2024)

https://www.home-assistant.io/blog/2024/12/04/release-202412/

<img width="585" alt="image" src="https://github.com/user-attachments/assets/4f463644-f4c3-43db-97d1-fa17b720348d">

**Comment by Remigius0815** [comment]
Same here

**Comment by dm82m** [comment]
Yes also here, but as the integration was not working for me due to #96 it makes no difference for me 🥴

**Comment by maddinhome** [comment]
My integration is still running... with version 2024.11.3 of HA. So I'll wait with the December update until Erik has perhaps found a solution to adapt to Python 3.13.

**Comment by maddinhome** [comment]
My integration is still running... with version 2024.11.3 of HA. So I'll wait with the December update until Erik has perhaps found a solution to adapt to Python 3.13.

**Comment by knonem** [comment]
Hi everyone,
for me it was fixed by changing to the latest versions of scrapy and twisted in the manifest.json and restarting HA:

...
```
"requirements": [
    "scrapyscript==1.1.*",
    "scrapy==2.12.*",
    "fuzzywuzzy==0.18.0",
    "twisted==24.11.0"
  ],
```
...

**However I'm only using the API!** 
Since this changes the dependencies in the "scapping"-part of Integration it might not work for everyone. Feel free to try it out, but this is only meant as quick fix.

**Comment by thartlieb** [comment]
Hi @knonem , thank you very much for this tip. 
Now it works again.
👍

**Comment by maddinhome** [comment]
Unfortunately for me it doesn't work with HA 2024.12.0. Sensors are lost. Back to 2024.11.3 with backup and the “old” manifest.json and it works again. I use both api and web. So in the “both” configuration.

**Comment by maddinhome** [comment]
I have to correct myself, I completely restarted my server (hard reset) and now it works...

**Comment by misterbond007** [comment]
> Unfortunately for me it doesn't work with HA 2024.12.0. Sensors are lost. Back to 2024.11.3 with backup and the “old” manifest.json and it works again. I use both api and web. So in the “both” configuration.

Same situation here.

**Comment by erikkastelec** [comment]
@knonem thank you for figuring this out. I created a new release with a fix. 

A restart of Home Assistant may be needed for requirements to upgrade. I will leave this open if we encounter any additional problems.

**Comment by Codeschnipsler** [comment]
I wanted to thank you for you fast reaction to aforementioned issue, @erikkastelec . The WEM addin works now after you provided the update. I can't judge if there is any difference in experience to prior as I was just installing and connecting for the first time when the issue popped up. 
So I am happy to pull the various data from the Weishaupt Heat pump. I am now starting to digest what I see and how I can use it to optimize the setup ;-{)

**Comment by Edelfalke** [comment]
> Hi everyone, for me it was fixed by changing to the latest versions of scrapy and twisted in the manifest.json and restarting HA:
> 
> ...
> 
> ```
> "requirements": [
>     "scrapyscript==1.1.*",
>     "scrapy==2.12.*",
>     "fuzzywuzzy==0.18.0",
>     "twisted==24.11.0"
>   ],
> ```
> 
> ...
> 
> **However I'm only using the API!** Since this changes the dependencies in the "scapping"-part of Integration it might not work for everyone. Feel free to try it out, but this is only meant as quick fix.

Hi Knonem, could you please explain how to update scrappy? 
I didn't find any howto.

**Comment by dm82m** [comment]
@Edelfalke this is already fixed in the newest release of the integration, just upgrade it.

**Comment by newslettersns2000** [comment]
I think I found something. When I restart Home Assistant the problem comes back, no matter how many times I restart HA, the problem remains, i.e. no data and the known login problems with the integration. If I restart my Fritzbox (Internet connection), the integration works again and all data is updated again. What has changed - After restarting the Fritzbox, the internet provider assigns a new IP address and since restarting the Fritzbox has nothing to do with Home Assistant, I suspect that Weishaupt is the problem.
